variable "name" {}
variable "machine_type" {}
variable "zone" {}
variable "gce_ssh_pub_key_file" {}
variable "common_ssh_pub_key_file" {}
variable "gce_ssh_user" {}
variable "network" {}
variable "subnetwork" {}
variable "network_ip" {}
variable "metadata_startup_script" {}